# Generated by Django 4.2.3 on 2023-07-24 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('in progress', 'In progress'), ('stored', 'Stored'), ('send', 'Send')], max_length=50)),
                ('prev_status', models.CharField(choices=[('new', 'New'), ('in progress', 'In progress'), ('stored', 'Stored'), ('send', 'Send')], default=None, max_length=255, null=True)),
                ('id_in_connected_db', models.IntegerField(default=None, null=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.synchconnection', verbose_name='Store')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
