# Generated by Django 4.2.3 on 2023-07-24 17:11

from django.db import migrations

from store_warehouse.orders.models import SynchConnection


def create_store_connection(apps, schema_editor):
    store = SynchConnection.objects.create(
        name='Store1',
        url='http://store:8001',
        token='-',
    )
    store.save()


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_store_connection),
    ]
