# Generated by Django 4.2.3 on 2023-07-22 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_warehouseorder_id_in_store_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouseorder',
            name='id_in_store',
        ),
        migrations.AddField(
            model_name='warehouseorder',
            name='id_in_connected_db',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
