# Generated by Django 4.2.3 on 2023-07-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_remove_warehouseorder_id_in_store_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseorder',
            name='synchronized',
            field=models.BooleanField(default=False),
        ),
    ]
