version: "3.10"

services:
  database_store:
    image: postgres:15
    container_name: database_store
    volumes:
      - postgres_data_store:/var/lib/postgresql/data/
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_store
  store:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: store
    depends_on:
      - database_store
    ports:
      - '8001:8001'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env.store
    command: sh -c "poetry run python manage.py migrate
                    && poetry run python3 manage.py createsuperuser --noinput --email admin@admin.com
                    && poetry run gunicorn -w 5 -b 0.0.0.0:8001 store_warehouse.wsgi"

  database_warehouse:
    image: postgres:15
    container_name: database_warehouse
    volumes:
      - postgres_data_warehouse:/var/lib/postgresql/data/
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_warehouse
  warehouse:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: warehouse
    depends_on:
      - database_warehouse
    ports:
      - '8002:8002'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env.warehouse
    command: sh -c "poetry run python manage.py migrate
                    && poetry run python3 manage.py createsuperuser --noinput --email admin@admin.com
                    && poetry run gunicorn -w 5 -b 0.0.0.0:8002 store_warehouse.wsgi"

volumes:
  postgres_data_store:
  postgres_data_warehouse:
