# Generated by Django 4.2.3 on 2023-07-24 17:10

from django.db import migrations
from django.contrib.auth.models import User


def create_admin(apps, schema_editor):
    admin_user = User.objects.create_user(username='admin', password='admin')
    admin_user.is_staff = True
    admin_user.is_superuser = True
    admin_user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_admin),
    ]
