# Generated by Django 4.2.3 on 2023-07-22 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeorder',
            name='id_in_warehouse',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='storeorder',
            name='order_number',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
