# Generated by Django 4.2.3 on 2023-07-24 17:11

from django.db import migrations

from store_warehouse.orders.models import SynchConnection


def create_warehouse_connection(apps, schema_editor):
    warehouse1 = SynchConnection.objects.create(
        name='Warehouse1',
        url='http://warehouse1:8002',
        token='-',
    )
    warehouse1.save()
    warehouse2 = SynchConnection.objects.create(
        name='Warehouse2',
        url='http://warehouse2:8003',
        token='-',
    )
    warehouse2.save()


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_warehouse_connection),
    ]
