# Generated by Django 4.2.3 on 2023-07-22 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_storeorder_id_in_warehouse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeorder',
            name='id_in_warehouse',
        ),
        migrations.AddField(
            model_name='storeorder',
            name='id_in_connected_db',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
