# Generated by Django 4.2.3 on 2023-07-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_storeorder_id_in_warehouse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeorder',
            name='synchronized',
            field=models.BooleanField(default=False),
        ),
    ]
