# Generated by Django 4.2.3 on 2023-07-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_storeorder_synchronized'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeorder',
            name='synchronized',
        ),
        migrations.AddField(
            model_name='storeorder',
            name='prev_status',
            field=models.CharField(choices=[('new', 'New'), ('in progress', 'In progress'), ('stored', 'Stored'), ('send', 'Send')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='storeorder',
            name='id_in_connected_db',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
