# Generated by Django 4.2.3 on 2023-07-23 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_storeorder_synchronized_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeorder',
            name='id_in_connected_db',
        ),
    ]
